name: Tests
on:
  pull_request:
    branches:
      - main

jobs:
  ios-tests:
    name: Test iOS
    runs-on: macos-12
    defaults:
      run:
        working-directory: ios
    steps:
      - uses: actions/checkout@v2
      - name: Cache gradle
        uses: actions/cache@v2.1.7
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          working-directory: ios
      - name: Run iOS tests
        run: bundle exec fastlane tests
  common-and-android-test:
    name: Test common module and Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Test common module and Android
        run: sh gradlew --no-daemon --stacktrace testReleaseUnitTest
